package github

import (
	"context"
	"fmt"
	"strings"

	gh "github.com/google/go-github/v58/github"
	"golang.org/x/oauth2"
)

// Client wraps the GitHub API for documentation-related operations.
type Client struct {
	api   *gh.Client
	owner string
	repo  string
}

// NewClient creates a new GitHub client authenticated with the given token.
func NewClient(token, owner, repo string) *Client {
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: token},
	)
	tc := oauth2.NewClient(context.Background(), ts)
	client := gh.NewClient(tc)

	return &Client{
		api:   client,
		owner: owner,
		repo:  repo,
	}
}

// PRDiff holds the diff information for a pull request.
type PRDiff struct {
	Files []PRFile
}

// PRFile represents a single changed file in a pull request.
type PRFile struct {
	Filename string
	Patch    string
	Status   string // "added", "removed", "modified", "renamed"
}

// GetPRDiff fetches the list of changed files and their diffs for a pull request.
func (c *Client) GetPRDiff(ctx context.Context, prNumber int) (*PRDiff, error) {
	files, _, err := c.api.PullRequests.ListFiles(ctx, c.owner, c.repo, prNumber, &gh.ListOptions{
		PerPage: 100,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list PR files: %w", err)
	}

	diff := &PRDiff{}
	for _, f := range files {
		diff.Files = append(diff.Files, PRFile{
			Filename: f.GetFilename(),
			Patch:    f.GetPatch(),
			Status:   f.GetStatus(),
		})
	}

	return diff, nil
}

// GetFileContent fetches the content of a file from the repository at the default branch.
func (c *Client) GetFileContent(ctx context.Context, path, ref string) (string, error) {
	fileContent, _, _, err := c.api.Repositories.GetContents(ctx, c.owner, c.repo, path, &gh.RepositoryContentGetOptions{
		Ref: ref,
	})
	if err != nil {
		return "", fmt.Errorf("failed to get file content for %s: %w", path, err)
	}
	if fileContent == nil {
		return "", fmt.Errorf("file %s is a directory, not a file", path)
	}

	content, err := fileContent.GetContent()
	if err != nil {
		return "", fmt.Errorf("failed to decode file content for %s: %w", path, err)
	}

	return content, nil
}

// CreateDocUpdatePR creates a new branch with updated documentation and opens a pull request.
func (c *Client) CreateDocUpdatePR(ctx context.Context, baseBranch string, docPath string, updatedContent string, originalPRNumber int) (*gh.PullRequest, error) {
	// Get the SHA of the base branch
	baseRef, _, err := c.api.Git.GetRef(ctx, c.owner, c.repo, "refs/heads/"+baseBranch)
	if err != nil {
		return nil, fmt.Errorf("failed to get base branch ref: %w", err)
	}

	// Create a new branch
	branchName := fmt.Sprintf("docs/update-%s-pr-%d", sanitizeBranchName(docPath), originalPRNumber)
	newRef := &gh.Reference{
		Ref:    gh.String("refs/heads/" + branchName),
		Object: baseRef.Object,
	}
	_, _, err = c.api.Git.CreateRef(ctx, c.owner, c.repo, newRef)
	if err != nil {
		return nil, fmt.Errorf("failed to create branch %s: %w", branchName, err)
	}

	// Get the current file to obtain its SHA (needed for update)
	currentFile, _, _, err := c.api.Repositories.GetContents(ctx, c.owner, c.repo, docPath, &gh.RepositoryContentGetOptions{
		Ref: branchName,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get current doc file: %w", err)
	}

	// Commit the updated documentation
	commitMsg := fmt.Sprintf("docs: update %s based on PR #%d", docPath, originalPRNumber)
	_, _, err = c.api.Repositories.UpdateFile(ctx, c.owner, c.repo, docPath, &gh.RepositoryContentFileOptions{
		Message: gh.String(commitMsg),
		Content: []byte(updatedContent),
		SHA:     currentFile.SHA,
		Branch:  gh.String(branchName),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update doc file: %w", err)
	}

	// Open a pull request
	prTitle := fmt.Sprintf("docs: update %s (triggered by PR #%d)", docPath, originalPRNumber)
	prBody := fmt.Sprintf("This PR was automatically generated by the Living Docs agent.\n\nIt updates `%s` to reflect changes made in PR #%d.\n\nPlease review the changes carefully before merging.", docPath, originalPRNumber)

	pr, _, err := c.api.PullRequests.Create(ctx, c.owner, c.repo, &gh.NewPullRequest{
		Title: gh.String(prTitle),
		Body:  gh.String(prBody),
		Head:  gh.String(branchName),
		Base:  gh.String(baseBranch),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create pull request: %w", err)
	}

	return pr, nil
}

// sanitizeBranchName cleans a file path for use in a git branch name.
func sanitizeBranchName(path string) string {
	s := strings.ReplaceAll(path, "/", "-")
	s = strings.ReplaceAll(s, ".", "-")
	s = strings.ReplaceAll(s, " ", "-")
	return strings.ToLower(s)
}
